## What is NumPy?
- NumPy is a python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- NumPy stands for Numerical Python.

### Why use NumPy?
NumPy is memory efficiency, meaning it can handle the vast amount of data more accessible than any other library. Besides, NumPy is very convenient to work with, especially for matrix multiplication and reshaping. On top of that, NumPy is fast. In fact, TensorFlow and Scikit learn to use NumPy array to compute the matrix multiplication in the back end. 

### how to install
If you have Python and PIP already installed on a system, then installation of NumPy is very easy.
Install it using this command:
- pip install numpy

after install numpy then import it by following code

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.17.4


## Numpy array
NumPy arrays are a bit like Python lists, but still very much different at the same time. For those of you who are new to the topic, let’s clarify what it exactly is and what it’s good for.
As the name kind of gives away, a NumPy array is a central data structure of the numpy library. The library’s name is actually short for "Numeric Python" or "Numerical Python". 

In [7]:
myPythonList = [1,9,8,3] # Simplest way to create an array in Numpy is to use Python List 
numpy_array_from_list = np.array(myPythonList) # To convert python list to a numpy array by using the object np.array. 
print(numpy_array_from_list)

[1 9 8 3]


In [8]:
a  = np.array([1,9,8,3]) # above operation in combine

### Shape of Array
You can check the shape of the array with the object shape preceded by the name of the array. In the same way, you can check the type with dtypes

In [14]:
a=np.array([1,2,3,4,5,6])
print(a.shape)
print(a.dtype)

(6,)
int64


### 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays

In [21]:
arr = np.array([1, 2, 3, 4, 5])
print(arr) 
print(arr.ndim)

[1 2 3 4 5]
1


### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.These are often used to represent matrix or 2nd order tensors.

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.These are often used to represent a 3rd order tensor.

In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr) 
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


## NumPy Array Indexing
### Access Array Elements
- Array indexing is the same as accessing an array element.
- You can access an array element by referring to its index number.
- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [24]:
arr = np.array([1, 2, 3, 4])
print(arr[0]) # print 0th item from array

1


In [25]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3]) #Get third and fourth elements from the following array and add them.

7


### Access 2-D and 3-D Array
- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
- To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [27]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[0, 1]) 
print('5th element on 2nd dim: ', arr[1, 4]) 

2nd element on 1st dim:  2
5th element on 2nd dim:  10


In [29]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Access the third element of the second array of the first array",arr[0, 1, 2]) 

Access the third element of the second array of the first array 6


### Slicing arrays
- Slicing in python means taking elements from one given index to another given index.
- We pass slice instead of index like this: [start:end].
- We can also define the step, like this: [start:end:step].
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) 
print(arr[4:]) # Slice elements from index 4 to the end of the array
print(arr[1:5:2]) #Return every other element from index 1 to index 5

[2 3 4 5]
[5 6 7]
[2 4]


### Slicing 2-D Arrays


In [36]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) # From the second element, slice elements from index 1 to index 4 (not included)
print(arr[0:2, 2]) # from both array return 2nd index

[7 8 9]
[3 8]


### Shape of Array
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

In [43]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr.shape)

(2, 5)


## Reshaping arrays
- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.
- By reshaping we can add or remove dimensions or change number of elements in each dimension.

### Reshape From 1-D to 2-D
- Convert the following 1-D array with 12 elements into a 2-D array.
- The outermost dimension will have 4 arrays, each with 3 elements

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Can We Reshape Into any Shape?
- Yes, as long as the elements required for reshaping are equal in both shapes.
- We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])

newarr = arr.reshape(3, 3)

print(newarr) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Flattening the arrays
- Flattening array means converting a multidimensional array into a 1D array. We can use reshape(-1) to do this.

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr) 

[1 2 3 4 5 6]


### Iterating Arrays
- Iterating means going through elements one by one.
- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
- If we iterate on a 1-D array it will go through each element one by one.

In [110]:
arr = np.array([1, 2, 3])
for x in arr:
    print(x) 

1
2
3


In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr: # iterateon 2d array
    print(x) 

[1 2 3]
[4 5 6]


In [55]:
for x in arr: # iterate on each scalar element 2-D array
    for y in x:
        print(y) 

1
2
3
4
5
6


### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations
#### Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality

In [61]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


#### Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating. NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered']

In [65]:
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


####  Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one. Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [70]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr): # Enumerate on above 1D array's elements
    print(idx, x) 

(0,) 1
(1,) 2
(2,) 3


In [71]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr): # Enumerate on above 2D array's elements
    print(idx, x) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Joining NumPy Arrays
- Joining means putting contents of two or more arrays in a single array.
- In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
- We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [72]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [87]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1) #Join two 2-D arrays along rows
print(arr)
arr = np.concatenate((arr1, arr2)) # join two 2-D array along column
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Joining Arrays Using Stack Functions
- Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
- We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
- We pass a sequence of arrays that we want to join to the concatenate() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [90]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))
print(arr) 

[[1 2 3]
 [4 5 6]]


#### Stacking Along Rows
- NumPy provides a helper function: hstack() to stack along rows.

In [91]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


#### Stacking Along Columns
- NumPy provides a helper function: Vstack() to stack along rows.

In [103]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### Splitting NumPy Arrays
- Splitting is reverse operation of Joining.
- Joining merges multiple arrays into one and Splitting breaks one array into multiple.
- We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [95]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print(newarr) 

[array([1, 2, 3]), array([4, 5, 6])]


In [102]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 2)
print(newarr) 

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


### Numpy Array search and Short
- You can search an array for a certain value, and return the indexes that get a match. To search an array, use the where() method.
- Sorting means putting elements in a ordered sequence. Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending. The NumPy ndarray object has a function called sort(), that will sort a specified array

In [109]:
arr=np.array([1,4,2,3,8,6,5])
print(np.where(arr==2)) # search on array
print(np.sort(arr)) # sort array

(array([2]),)
[1 2 3 4 5 6 8]


### Numpy  Arrange
Sometimes, you want to create values that are evenly spaced within a defined interval. For instance, you want to create values from 1 to 10; you can use numpy.arange() function 
- syntax= numpy.arange(start, stop,step) 

In [113]:
print(np.arange(1, 11))
print(np.arange(1,11,2))

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


## Random Numbers in NumPy
Random number does NOT mean a different number every time. Random means something that can not be predicted logically


### Generate Random Number
- NumPy offers the random module to work with random numbers
- randint() method generate random integer number
- The random module's rand() method returns a random float between 0 and 1

In [124]:
x = np.random.randint(10) # generate one random number between 0 to 10
print(x) 
x=np.random.randint(low=2,high=20,size=5) # generate five random number between 2 to 20
print(x)

2
[11 18 15 16  4]


In [130]:
x=np.random.rand()# generate one random number between 0 to 1
print(x)
x=np.random.rand(5) #generate five random number between 0 to 1
print(x)

0.7205110296939016
[0.81075527 0.76133124 0.28338823 0.99734074 0.95367171]


### Random Distribution
A random distribution is a set of random numbers that follow a certain probability density function.We can generate random numbers based on defined probabilities using the choice() method of the random module.
The choice() method allows us to specify the probability for each value.The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur

In [133]:
x =np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.], size=(100))

print(x) 

[7 5 7 7 7 7 7 7 5 7 7 7 7 3 7 5 7 7 7 7 7 5 5 7 7 3 5 7 7 7 3 5 3 7 7 5 7
 5 7 3 3 7 7 5 7 3 7 7 7 5 7 7 7 7 5 5 7 7 5 7 7 7 7 5 7 3 5 5 7 7 7 5 7 7
 5 7 7 5 7 7 7 7 3 5 7 7 7 7 5 5 5 5 3 7 3 7 5 5 5 7]


In [143]:
x =np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3,5)) # return an 2-D array with 3 rows, each containging 5 values
print(x) 


[[3 5 7 7 5]
 [5 5 5 7 7]
 [7 7 3 7 3]]


### Random Permutations
A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.
The NumPy Random module provides two methods for this: shuffle() and permutation()
- The shuffle() method makes changes to the original array
- Shuffle means changing arrangement of elements in-place
- The permutation() method returns a re-arranged array (and leaves the original array un-changed)
- in case of permutation for multidimentional only suffled it's first index

In [148]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr) 
arr = np.array([1, 2, 3, 4, 5])
print(np.random.permutation(arr)) 

[5 4 1 3 2]
[3 5 2 1 4]


In [155]:
x=np.random.randint(2,50,(4,5)) # for multidimensional only suffled first index
print(x)
print(np.random.permutation(x)) 

[[46 22 40 49 41]
 [34 10  6  2 20]
 [43 37  9 32  3]
 [10 31 37 23 35]]
[[34 10  6  2 20]
 [43 37  9 32  3]
 [46 22 40 49 41]
 [10 31 37 23 35]]


## some Numpy Array Method
### Minimum
- compair two array and return new array contain element wise minima

### Maximum
- compair two array and return a new array contain element wise maxima

### Max
- return maximum along the axis

### Min 
- return minimum along the axis

### Sum
- sum of array element over a given axis

### insert 
-  insert the value along given axis before the given indices

### append
- append the value end of the array


In [162]:
a1=np.array([4,7,6,7])
a2=np.array([5,9,2,3])
print(np.minimum(a1,a2))
print(np.maximum(a1,a2))
print(np.min(a1))
print(np.max(a2))
print(np.sum(a1))
print(np.insert(a1,3,[1,2,3],axis=0))
print(np.append(a2,[2,3,4],axis=0))

[4 7 2 3]
[5 9 6 7]
4
9
24
[4 7 6 1 2 3 7]
[5 9 2 3 2 3 4]
