# Python

### Topic
* Data Structures(String,List,Tuple,Dictionry)
* if and else statement
* Loop(For,While)
* Function
* Class

## String
- A string is a sequence of characters.A character is simply a symbol.Ex- the English language has 26 characters.
- strings, which are immutable. \ is used as an escape character.
- create them simply by enclosing characters in quotes. Python treats single quotes the same as double quotes.

In [3]:
print("Welcome to Mpercept")

Welcome to Mpercept


In [3]:
print('ram \'s')

ram 's


In [2]:
print('First line.\nSecond line')

First line.
Second line


In [1]:
print('C:\some\name')

"C:\some
ame"


In [6]:
print(r'C:\some\name')

C:\some\name


In [7]:
string1='hello'

In [8]:
#string1[1]='r' #Immutable

In [9]:
string1[1]

'e'

In [10]:
string1[1:4]

'ell'

# list

- Lists They are one of the most versatile data structure in Python. A list can simply be defined by writing a list of comma separated values in square brackets. Lists might contain items of different types, but usually the items all have the same type. 
- Python lists are mutable and individual elements of a list can be changed.


In [11]:
squares = [] # empty list
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

In [12]:
squares[0]  # indexing returns the item

1

In [13]:
squares[-1]

25

In [14]:
squares[-3:]  # slicing returns a new list

[9, 16, 25]

In [15]:
squares[:]


[1, 4, 9, 16, 25]

In [16]:
len(squares)

5

In [17]:
x=[]
for i in range(10):
    x.append(i)
print(x)

y=[x for x in range(10)]
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Tuple

- A tuple is represented by a number of values separated by commas. Tuples are immutable and the output is surrounded by parentheses so that nested tuples are processed correctly. Additionally, even though tuples are immutable, they can hold mutable data if needed.Since Tuples are immutable and can not change, they are faster in processing as compared to lists. Hence, if your list is unlikely to change, you should use tuples, instead of lists.

In [18]:
empty = ()

In [19]:
tuple_example = 0, 1, 4, 9, 16, 25

In [20]:
tuple_example # in parenthesis

(0, 1, 4, 9, 16, 25)

In [21]:
tuple_example[2]

4

In [22]:
tuple_example[:]

(0, 1, 4, 9, 16, 25)

In [23]:
tuple_example[2] = 6 # immutable so error

TypeError: 'tuple' object does not support item assignment

# Dictionary
- It is an unordered set of key: value pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: {}. 

In [24]:
my_dict = {1: 'apple', 2: 'ball'}
print(my_dict)
print(my_dict[1])

{1: 'apple', 2: 'ball'}
apple


In [25]:
# Access elements from a dictionary
my_dict = {'name': 'Jack', 'age': 26}
print(my_dict['name'])
print(my_dict['age'])

Jack
26


In [26]:
my_dict.keys()

dict_keys(['name', 'age'])

In [27]:
my_dict.values()

dict_values(['Jack', 26])

In [28]:
for k, v in my_dict.items():
    print(k, v)


name Jack
age 26


# Python If ... Else

In [29]:
a = 10
b = 20
if b > a:
    print("b is greater than a")
else:
    print("a is greater than b")


b is greater than a


In [30]:

a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

a is greater than b


# While 

In [31]:
 i = 1
while i < 6:
  print(i,end="")
  i += 1

12345

In [32]:
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1 

1
2
3


# For loop

In [33]:
for m in "MPercept":
    print(m ,end='')

MPercept

In [34]:
student=['ram','shyam','hari','ravan']
for x in student:
    print(x)

ram
shyam
hari
ravan


In [35]:
test = "MPercept"
for m in range(len(test)):
 	print('{0} is in {1} position'.format(test[m],m))

M is in 0 position
P is in 1 position
e is in 2 position
r is in 3 position
c is in 4 position
e is in 5 position
p is in 6 position
t is in 7 position


# Function
- A function is a block of code which only runs when it is called. You can pass data, known as parameters, into a function. A function can return data as a result.

In [36]:
 # empty function
def my_function():
    pass

In [37]:
def my_function():
    print('Hello from MPercept!')

In [38]:
my_function()

Hello from MPercept!


In [39]:
 def my_function(name):
    print('Hello, ' + name + '!')

my_function('World')

Hello, World!


In [40]:
def add(a,b):
    return a+b
add(4,5)

9

In [41]:
def tuple_arg(*args):
    print(args)
    print(type(args))

In [42]:
tuple_arg(1,2,3,4)

(1, 2, 3, 4)
<class 'tuple'>


In [43]:
def dict_args(**kwargs):
    for k,v in kwargs.items():
        print(k,':',v)
dict_args(Name='ram',marks=100)

In [44]:
dict_args(Name='ram',marks=100)

Name : ram
marks : 100


In [45]:

def my_function(*args, **kwargs):
    print(args, type(args))
    print(kwargs, type(kwargs))
my_function(1, 4, 'python', a=4, b=6, planet='earth')

(1, 4, 'python') <class 'tuple'>
{'a': 4, 'b': 6, 'planet': 'earth'} <class 'dict'>


#  Class and Object
- Python is an object oriented programming language. Almost everything in Python is an object, with its attributes and methods.A class is like a blueprint for creating objects.

In [46]:
class Person:
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def description(self):
        return "{} is {} years old.".format(self.name, self.age)
    
    def increase_age(self):
        self.age += 1

In [47]:
 p1 = Person('harry', 20)
print(p1.description())
p1.increase_age()
print(p1.description())


harry is 20 years old.
harry is 21 years old.


In [48]:
class Student(Person):
    
    def set_result(self, x):
        self.result = x
    
    def description(self):
        print( "Name: {}, Age: {}, Result: {}".format(self.name, self.age, self.result))
    
s1 = Student('ram', 20)
s1.set_result('Pass')
s1.description()
s1.increase_age()
s1.description()

Name: ram, Age: 20, Result: Pass
Name: ram, Age: 21, Result: Pass


# Numpy

## topic
- Array Creation
- Mathematical Iperation on arrays
- Reshapeing
- Indexing and Slicing
- Default array Generation like ones and Zeros
- Random module to generate array


# Numpy
- NumPy is a Python package which stands for ‘Numerical Python’.
- NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [49]:
import numpy as np

In [50]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [51]:
a.dtype

dtype('int32')

In [52]:
b = np.array([(1.5,2,3), (4,5,6)])
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [53]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [55]:
c = np.arange(24).reshape(2,3,4)

In [56]:
a = np.array( [20,30,40,50] )
b = np.arange(4)
b

array([0, 1, 2, 3])

In [57]:
c = a-b
c

array([20, 29, 38, 47])

In [58]:
a+b

array([20, 31, 42, 53])

In [59]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [60]:
c.min()

20

In [61]:
c.max()

47

In [62]:
c.argmax()

3

In [63]:
c.sum()

134

In [64]:
b = np.arange(12).reshape(3,4)
print(b)
x=np.arange(12).reshape(-1,1)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [65]:
b.sum(axis=0)  # sum of each column


array([12, 15, 18, 21])

In [66]:
b.min(axis=1)

array([0, 4, 8])

In [67]:
a = np.arange(10)**3
a


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [68]:
a[2]

8

In [69]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [70]:
a[ : :-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [71]:
np.ones(3)

array([1., 1., 1.])

In [72]:
np.zeros(3)

array([0., 0., 0.])

In [73]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.random.rand(5)

array([0.26899222, 0.17787452, 0.61523128, 0.28206278, 0.79157712])

In [76]:
np.random.randn(5,5)

array([[ 0.08510418, -0.68600451, -0.54574364, -0.06862352,  0.09468943],
       [ 1.55511296,  2.1860944 ,  0.17080273, -0.2891509 ,  0.33232377],
       [-0.71788104,  0.82688165,  1.21399224, -0.29262816,  0.96307323],
       [ 0.03745148,  0.34548353,  0.36988292,  0.63950129, -0.42761484],
       [-0.42827269,  0.55872487, -2.05803435,  0.09058042,  0.63301983]])

In [77]:
np.random.randint(1,100,10)

array([31,  2, 41, 32, 54, 79, 45, 38, 93, 38])

In [78]:
z=np.arange(20)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
z<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [80]:
z[z<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])